export const leadConstants = {

    ADD_LEAD_REQUEST: 'ADD_LEAD_REQUEST',
    ADD_LEAD_SUCCESS: 'ADD_LEAD_SUCCESS',
    ADD_LEAD_FAILURE: 'ADD_LEAD_FAILURE',

    GET_LEADS_REQUEST: 'GET_LEADS_REQUEST',
    GET_LEADS_SUCCESS: 'GET_LEADS_SUCCESS',
    GET_LEADS_FAILURE: 'GET_LEADS_FAILURE',

    UPLOAD_EXCEL_REQUEST: 'UPLOAD_EXCEL_REQUEST',
    UPLOAD_EXCEL_SUCCESS: 'UPLOAD_EXCEL_SUCCESS',
    UPLOAD_EXCEL_FAILURE: 'UPLOAD_EXCEL_FAILURE',

    EDIT_LEAD_REQUEST: 'EDIT_LEAD_REQUEST',
    EDIT_LEAD_SUCCESS: 'EDIT_LEAD_SUCCESS',
    EDIT_LEAD_FAILURE: 'EDIT_LEAD_FAILURE',
};
