export const sellerConstants = {
  ADD_SELLER_REQUEST: "ADD_SELLER_REQUEST",
  ADD_SELLER_SUCCESS: "ADD_SELLER_SUCCESS",
  ADD_SELLER_FAILURE: "ADD_SELLER_FAILURE",
  ADD_SELLER_CLEAR: "ADD_SELLER_CLEAR",
};
