export const settingConstants = {

    GET_SHARE_LINK_SETTING_REQUEST: 'GET_SHARE_LINK_SETTING_REQUEST',
    GET_SHARE_LINK_SETTING_SUCCESS: 'GET_SHARE_LINK_SETTING_SUCCESS',
    GET_SHARE_LINK_SETTING_FAILURE: 'GET_SHARE_LINK_SETTING_FAILURE',

    EDIT_SHARE_LINK_SETTING_REQUEST: 'EDIT_SHARE_LINK_SETTING_REQUEST',
    EDIT_SHARE_LINK_SETTING_SUCCESS: 'EDIT_SHARE_LINK_SETTING_SUCCESS',
    EDIT_SHARE_LINK_SETTING_FAILURE: 'EDIT_SHARE_LINK_SETTING_FAILURE',

};